{{ config(materialized='view')}}

SELECT
ORDER_ID,
CUSTOMER_ID,
EMPLOYEE_ID,
ORDER_DATE,
REQUIRED_DATE,
SHIPPED_DATE,
SHIP_VIA AS SHIPPER_ID,
FREIGHT,
SHIP_NAME,
SHIP_ADDRESS,
SHIP_CITY,
SHIP_REGION,
SHIP_COUNTRY
FROM {{ source('raw_northwind','orders')}}