{{ config(materialized='view')}}

SELECT
PRODUCT_ID, 
UNIT_PRICE,
CATEGORY_ID, 
SUPPLIER_ID, 
DISCONTINUED AS DISCONTINUED_STATUS, 
PRODUCT_NAME, 
REORDER_LEVEL, 
UNITS_IN_STOCK, 
UNITS_ON_ORDER, 
QUANTITY_PER_UNIT
FROM {{ source('raw_northwind','products')}}